//
//  TodoInteractor.swift
//  TodoListCleanArc
//
//  Created by Reza Harris on 26/10/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation
import CloudKit

struct RecordType {
    static let Todos = "TodoList"
}


protocol TodoBusinessLogic
{
    func fetchData(request: TodoModels.Fetch.Request)
}

protocol TodoDataStore
{
    //var name: String { get set }
}

class TodoInteractor: TodoBusinessLogic, TodoDataStore
{
    var presenter: TodoPresentationLogic?
    var todoWorker = TodoWorker()
    var todos: [Todo] = []
    
    
    func fetchData(request: TodoModels.Fetch.Request)
    {
        // Masih Error, Harus di pakein Future<Blabla>
//        todoWorker.fetch(recordType: RecordType.Todos, completion: { (result) in
//            switch result {
//            case .success(let newItem):
//                self.todos.append(newItem)
//                print(self.todos)
//            case .failure(let err):
//                print("Error: \(err.localizedDescription)")
//            }
//        })
        
        todos.append(Todo(id: UUID(uuidString: "b2acd147-2004-4b41-88b3-eb983ee93171")!, recordID: CKRecord.ID(recordName: "b2acd147-2004-4b41-88b3-eb983ee93171"), text: "Let's Coding"))
        todos.append(Todo(id: UUID(uuidString: "9c39dbc2-ea15-476d-8303-1c58a8637d63")!, recordID: CKRecord.ID(recordName: "368d99ca-ea8e-43a5-a7bd-dbe4fa7da764"), text: "Jogging Hola laa"))
        
        let response = TodoModels.Fetch.Response(todos: todos)
        presenter?.presentTodo(response: response)
    }
}
