//
//  TodoPresenter.swift
//  TodoListCleanArc
//
//  Created by Reza Harris on 26/10/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//// tambahin case kl dia lg loading, error dll, yg mau ditampilin apa


import SwiftUI
import Combine

protocol TodoPresentationLogic
{
  func presentTodo(response: TodoModels.Fetch.Response)
}

class TodoPresenter: ObservableObject, TodoPresentationLogic
{
    
    @Published var todos: [Todo] = []
  
  // MARK: Do something
  
  func presentTodo(response: TodoModels.Fetch.Response)
  {
      todos = response.todos
  }
}
