//
//  TodoModels.swift
//  TodoListCleanArc
//
//  Created by Reza Harris on 26/10/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

// bisa buat usecase di sini

import Foundation
import CloudKit

enum TodoModels
{
  // MARK: Use cases
  enum Fetch
  {
    struct Request
    {
    }
    struct Response
    {
        var todos: [Todo]
    }
    struct ViewModel
    {
    }
  }
}


struct Todo: Identifiable {
    var id = UUID()
    var recordID: CKRecord.ID?
    var text: String = ""
}
